export const GLOSSARY = {
  S11:          'Coefficiente di riflessione — misura quanta potenza viene riflessa all\'ingresso. Ideale < −10 dB.',
  VSWR:         'Voltage Standing Wave Ratio — rapporto d\'onda stazionaria. Ideale = 1:1 (< 2:1 accettabile).',
  SWR:          'Standing Wave Ratio — sinonimo di VSWR.',
  dB:           'Decibel — scala logaritmica. Ogni −10 dB = 10× meno potenza riflessa.',
  FDTD:         'Finite-Difference Time-Domain — metodo numerico per simulare la propagazione elettromagnetica.',
  λ:            'Lunghezza d\'onda = c / f  (c = 299 792 km/s). Determina le dimensioni fisiche dell\'antenna.',
  MHz:          'Megahertz — milioni di cicli al secondo.',
  GHz:          'Gigahertz — miliardi di cicli al secondo.',
  feed:         'Feed point — punto di alimentazione dove il cavo coassiale si connette all\'antenna.',
  'Return Loss': 'Perdita di ritorno = −S11 in dB. Più alto = meglio.',
  resonance:    'Frequenza di risonanza — dove S11 è minimo e l\'antenna trasferisce il massimo di potenza.',
  εr:           'Permittività relativa del substrato dielettrico (patch antenna). FR4 ≈ 4.4.',
  gain:         'Guadagno — rapporto tra la potenza irradiata in una direzione e quella di un\'antenna isotropa. In dBi.',
  dBi:          'Decibel rispetto ad un\'antenna isotropa ideale. Misura il guadagno direzionale.',
  impedance:    'Impedenza di ingresso — rapporto tensione/corrente al feed point. Ideale: 50 Ω per coassiale standard.',
  bandwidth:    'Larghezza di banda — intervallo di frequenze dove S11 < −10 dB (VSWR < 2:1).',
  PML:          'Perfectly Matched Layer — strato assorbente ai bordi della griglia FDTD che simula lo spazio libero infinito.',
  NrTS:         'Numero di timestep — quanti passi temporali esegue la simulazione FDTD prima di fermarsi.',
};
